version: '3.8'

services:
  interview-bot:
    build: .
    container_name: telegram-interview-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghi
      - ADMIN_CHAT_ID=123456789
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-data: